### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by perimore** [aristanetworks/goarista#17]
Hi,

After installing go and the gnmi client I get the following error:

gnmi -addr localhost:46030 -username admin get '/'
/:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1388036]

goroutine 1 [running]:
main.get(0x14e22a0, 0xc4200a9b90, 0x14e2460, 0xc4200bc040, 0xc4201923e0, 0x1, 0x1, 0x1, 0x0)
	/Users/sean/go/src/github.com/aristanetworks/goarista/cmd/gnmi/main.go:132 +0x1e6
main.main()
	/Users/sean/go/src/github.com/aristanetworks/goarista/cmd/gnmi/main.go:77 +0x7c5

Any idea why this might be happening?

Thanks.

**Comment by 7AC** [comment]
I just tested with the latest and it works, the worst I could get was this with a moderately loaded device:

```
F0406 11:00:19.266509    5123 main.go:81] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9891676 vs. 4194304)
exit status 255
```

The line numbers look off, are you using the latest version?
